/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAITudreYT9wA14kOe9GnxjiE9viSIQDP4',
    appId: '1:802096114944:web:a9427b405f3363bee6d7e5',
    messagingSenderId: '802096114944',
    projectId: 'photomall10',
    authDomain: 'photomall10.firebaseapp.com',
    storageBucket: 'photomall10.appspot.com',
    measurementId: 'G-5ZBD28X202',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPmax1KsI2KkbYYFjXzue9C2oagal0a2Y',
    appId: '1:802096114944:android:7539f05f435d1907e6d7e5',
    messagingSenderId: '802096114944',
    projectId: 'photomall10',
    storageBucket: 'photomall10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQDxTEIrkVNfllhHOOHQ3kuHhjMZpOX7k',
    appId: '1:802096114944:ios:33828c816623b5dde6d7e5',
    messagingSenderId: '802096114944',
    projectId: 'photomall10',
    storageBucket: 'photomall10.appspot.com',
    iosBundleId: 'com.example.photomallConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQDxTEIrkVNfllhHOOHQ3kuHhjMZpOX7k',
    appId: '1:802096114944:ios:33828c816623b5dde6d7e5',
    messagingSenderId: '802096114944',
    projectId: 'photomall10',
    storageBucket: 'photomall10.appspot.com',
    iosBundleId: 'com.example.photomallConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAITudreYT9wA14kOe9GnxjiE9viSIQDP4',
    appId: '1:802096114944:web:f03ddb325ad3874de6d7e5',
    messagingSenderId: '802096114944',
    projectId: 'photomall10',
    authDomain: 'photomall10.firebaseapp.com',
    storageBucket: 'photomall10.appspot.com',
    measurementId: 'G-GX1TTTCH64',
  );
}
*/
